apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: flux-system
spec:
  releaseName: cilium
  targetNamespace: cilium
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: "1.20.0-pre.2"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  install:
    crds: CreateReplace
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    kubeProxyReplacement: true
    securityContext:
      capabilities:
        ciliumAgent: [CHOWN, KILL, NET_ADMIN, NET_RAW, IPC_LOCK, SYS_ADMIN, SYS_RESOURCE, DAC_OVERRIDE, FOWNER, SETGID, SETUID]
        cleanCiliumState: [NET_ADMIN, SYS_ADMIN, SYS_RESOURCE]
    cni:
      exclusive: false
    l2announcements:
      enabled: true
    externalIPs:
      enabled: true
    gatewayAPI:
      enabled: true
