apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-token
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: ghcr-creds
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        username: Samuelnorth47
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: GHCR_TOKEN
