apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-csi-config
  namespace: proxmox-csi-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: proxmox-csi-config
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        config.yaml: |
          clusters:
            - url: https://cluster.proxmox.home.arpa:8006/api2/json
              insecure: true
              token_id: "kubernetes-csi@pve!csi"
              token_secret: "{{ .proxmox_csi_token }}"
              region: k8s-home-lab
  data:
    - secretKey: proxmox_csi_token
      remoteRef:
        key: PROXMOX_CSI_TOKEN

   
    
  
