apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dockerio-token
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
      name: dockerio-creds
      template:
        type: kubernetes.io/dockerconfigjson
        engineVersion: v2
        data:
          .dockerconfigjson: |
            {
              "auths": {
                "https://index.docker.io/v1/": {
                  "username": "samuelnorth47",
                  "password": "{{ .password }}"
                },
                "docker.io": {
                  "username": "samuelnorth47",
                  "password": "{{ .password }}"
                },
                "registry-1.docker.io": {
                  "username": "samuelnorth47",
                  "password": "{{ .password }}"
                }
              }
            }
  data:
    - secretKey: password
      remoteRef:
        key: DOCKERIO_TOKEN
