# clusters/test-cluster/configuration.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-configs
  interval: 10m
  path: ./apps/controllers
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
